### ISSUE TITLE
crear partial del footer

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-09#16]
El footer es un gran candidato para armar como partial y replicarlo en todas las paginas

https://github.com/0623CIFSNCN05LAED/grupo-09/blob/d77eac3b2a28afae9aab92af23501f6d15accbab/src/views/index.ejs#L90-L118

**Comment by Fernando-Lopez-86** [comment]
ok Luis, nos faltaba crear el partial para el footer, corregido
